
name: "Gold Futures"
key: "gold"
type: "commodity"
topic: "gold"
indexType: "futures"
symbol: "GCJ4"
endpoint: "https://www.investing.com/"
endpointExt: "commodities/gold"
nameXpath: "/html/body/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/h1[1]" 
priceXpath:	"/html/body/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]"