
name: "Meta"
key: "meta"
type: "stock"
topic: "meta"
indexType: "equities"
symbol: "META"
endpoint: "https://www.investing.com/"
endpointExt: "equities/facebook-inc"
nameXpath: "/html/body/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/h1[1]" 
priceXpath:	"/html/body/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]"