
name: "S&P 500"
key: "spx500"
type: "indices"
topic: "s&p"
indexType: "index"
symbol: "SPX"
endpoint: "https://www.investing.com/"
endpointExt: "indices/us-spx-500"
nameXpath: "/html/body/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/h1[1]" 
priceXpath:	"/html/body/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]"