
name: "Tesla"
key: "tesla"
topic: "tesla"
type: "stock"
indexType: "equities"
symbol: "TSLA"
endpoint: "https://www.investing.com/"
endpointExt: "equities/tesla-motors"
priceXpath: "//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[1]/div[3]/div[1]/div[3]/div[2]/span[1]"
nameXpath: "/html/body/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/h1[1]"
	# Name        string `yaml:"name"`
	# Key         string `yaml:"key"`
	# Topic       string `yaml:"topic"`
	# IndexType   string `yaml:"indexType"`
	# Symbol      string `yaml:"symbol"`
	# Endpoint    string `yaml:"endpoint"`
	# EndpointExt string `yaml:"endpointExt"`
	# NameXpath   string `yaml:"nameXpath"`
	# PriceXpath  string `yaml:"priceXpath"`